kind = "api"
previewPath = "/api" # TODO - should be excluded from preview in the first place
title = "API Server"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8080
name = "API Server"
paths = ["/api", "/"]
development.run = "pnpm --filter @workspace/api-server run dev"
production.build.args = ["sh", "-c", "pnpm --filter @workspace/elevator-tracker run build && node artifacts/api-server/build.mjs"]
production.build.env.NODE_ENV = "production"
production.build.env.BASE_PATH = "/"
production.build.env.PORT = "23706"
production.run.args = ["node", "--enable-source-maps", "artifacts/api-server/dist/index.mjs"]
production.run.env.PORT = "8080"
production.run.env.NODE_ENV = "production"
production.health.startup.path = "/api/healthz"
