// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dashboard/DashA.tsx": () => import("../components/mockups/dashboard/DashA.tsx"),
  "./components/mockups/dashboard/DashB.tsx": () => import("../components/mockups/dashboard/DashB.tsx"),
  "./components/mockups/dashboard/DashC.tsx": () => import("../components/mockups/dashboard/DashC.tsx"),
  "./components/mockups/dashboard-layouts/GridCards.tsx": () => import("../components/mockups/dashboard-layouts/GridCards.tsx"),
  "./components/mockups/dashboard-layouts/LeftRail.tsx": () => import("../components/mockups/dashboard-layouts/LeftRail.tsx"),
  "./components/mockups/dashboard-layouts/PriorityPyramid.tsx": () => import("../components/mockups/dashboard-layouts/PriorityPyramid.tsx"),
  "./components/mockups/dashboard-v2/CommandCenter.tsx": () => import("../components/mockups/dashboard-v2/CommandCenter.tsx"),
  "./components/mockups/dashboard-v2/ScorecardGrid.tsx": () => import("../components/mockups/dashboard-v2/ScorecardGrid.tsx"),
  "./components/mockups/dashboard-v2/TimelineFirst.tsx": () => import("../components/mockups/dashboard-v2/TimelineFirst.tsx"),
  "./components/mockups/dashboard-vibes/Blueprint.tsx": () => import("../components/mockups/dashboard-vibes/Blueprint.tsx"),
  "./components/mockups/dashboard-vibes/CleanRoom.tsx": () => import("../components/mockups/dashboard-vibes/CleanRoom.tsx"),
  "./components/mockups/dashboard-vibes/Dusk.tsx": () => import("../components/mockups/dashboard-vibes/Dusk.tsx"),
  "./components/mockups/login-variants/CommandCenter.tsx": () => import("../components/mockups/login-variants/CommandCenter.tsx"),
  "./components/mockups/login-variants/HorizontalCard.tsx": () => import("../components/mockups/login-variants/HorizontalCard.tsx"),
  "./components/mockups/login-variants/LayoutA.tsx": () => import("../components/mockups/login-variants/LayoutA.tsx"),
  "./components/mockups/login-variants/LayoutB.tsx": () => import("../components/mockups/login-variants/LayoutB.tsx"),
  "./components/mockups/login-variants/LayoutC.tsx": () => import("../components/mockups/login-variants/LayoutC.tsx"),
  "./components/mockups/login-variants/RefinedA.tsx": () => import("../components/mockups/login-variants/RefinedA.tsx"),
  "./components/mockups/login-variants/RefinedB.tsx": () => import("../components/mockups/login-variants/RefinedB.tsx"),
  "./components/mockups/login-variants/SplitScreen.tsx": () => import("../components/mockups/login-variants/SplitScreen.tsx"),
  "./components/mockups/inspection-form/CompactInspector.tsx": () => import("../components/mockups/inspection-form/CompactInspector.tsx"),
  "./components/mockups/inspection-form/StatusDashboard.tsx": () => import("../components/mockups/inspection-form/StatusDashboard.tsx"),
  "./components/mockups/inspection-form/TimelineFlow.tsx": () => import("../components/mockups/inspection-form/TimelineFlow.tsx")
};
