// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/login-variants/CommandCenter.tsx": () => import("../components/mockups/login-variants/CommandCenter.tsx"),
  "./components/mockups/login-variants/HorizontalCard.tsx": () => import("../components/mockups/login-variants/HorizontalCard.tsx"),
  "./components/mockups/login-variants/SplitScreen.tsx": () => import("../components/mockups/login-variants/SplitScreen.tsx")
};
